# Generated by Django 3.2.19 on 2023-07-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('like', models.BooleanField(default=False)),
                ('writing_time', models.DateTimeField(auto_now=True)),
                ('post_photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
