# Generated by Django 3.2.19 on 2023-07-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20230718_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
