# Generated by Django 3.2.19 on 2023-07-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_post_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='importance',
        ),
    ]
